[package]
name = "tinytickets_backend"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "tinytickets_backend"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.8.9"
chrono = { version = "0.4.44", features = ["serde"] }
deadpool-diesel = { version = "0.6.1", features = ["sqlite"] }
diesel = { version = "2.3.9", features = ["chrono", "returning_clauses_for_sqlite_3_35", "sqlite"] }
diesel_migrations = "2.3.2"
handlebars = { version = "6.4.1", features = ["dir_source"] }
http = "1.4.1"
image = "0.25.10"
lettre = "0.11.22"
libsqlite3-sys = { version = "0.37.0", features = ["bundled"] }
rand = "0.10.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
serde_trim = "1.1.0"
tokio = { version = "1.52.3", features = ["full"] }
tokio-util = { version = "0.7.18", default-features = false, features = ["io"] }
tower-http = { version = "0.6.11", default-features = false, features = ["cors", "fs"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[target.'cfg(unix)'.dependencies]
openssl = { version = "0.10.80", features = ["vendored"] }

[dev-dependencies]
reqwest = { version = "0.13.4", default-features = false, features = ["cookies", "json", "stream"] }
